version: "3.9"

services:
  mysql:
    image: mysql:9.2
    container_name: petclinic-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # postgres:
  #   image: postgres:17.5
  #   container_name: petclinic-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: petclinic
  #     POSTGRES_USER: petclinic
  #     POSTGRES_DB: petclinic
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U petclinic"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  petclinic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petclinic-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/petclinic
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic

volumes:
  mysql_data:
  postgres_data:
